
package publicar;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NombreFuncionRepetidoException", targetNamespace = "http://publicar/")
public class NombreFuncionRepetidoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NombreFuncionRepetidoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NombreFuncionRepetidoException_Exception(String message, NombreFuncionRepetidoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NombreFuncionRepetidoException_Exception(String message, NombreFuncionRepetidoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.NombreFuncionRepetidoException
     */
    public NombreFuncionRepetidoException getFaultInfo() {
        return faultInfo;
    }

}
