
package publicar;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UsuarioNoEsEspectadorException", targetNamespace = "http://publicar/")
public class UsuarioNoEsEspectadorException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioNoEsEspectadorException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioNoEsEspectadorException_Exception(String message, UsuarioNoEsEspectadorException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UsuarioNoEsEspectadorException_Exception(String message, UsuarioNoEsEspectadorException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.UsuarioNoEsEspectadorException
     */
    public UsuarioNoEsEspectadorException getFaultInfo() {
        return faultInfo;
    }

}
